name: Deploy to EC2

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy files to EC2
        run: |
          rsync -avz --exclude="node_modules" ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/

      - name: Install Node.js and PM2 on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Update system
            sudo apt update && sudo apt upgrade -y

            # Install curl
            sudo apt install -y curl

            # Install Node.js 22.x
            curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt install -y nodejs
            
            
            sudo npm install -g @angular/cli
            
            # Install PM2 globally if not installed
            if ! command -v pm2 >/dev/null 2>&1; then
              sudo npm install -g pm2
            fi

            # Ensure PM2 startup is configured only once
            if ! systemctl list-units --full -all | grep -q pm2-ubuntu; then
              # Setup PM2 startup service
              pm2 startup systemd -u ubuntu --hp /home/ubuntu | tail -n 1 | sudo bash
            fi
          EOF

      - name: Restart app
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/app
            npm install
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
          EOF
      - name: Notify deployment success
        run: echo "Deployment to EC2 completed successfully."
